### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by oksromn** [robinst/taglib-ruby#90]
I deployed my rails application on Google Kubernetes Engine.
```
ruby '2.5.1'
rails '5.1.7'
```

Server: 
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
```

When I try to use any method from taglib-ruby library, I get an error. For example:

`TagLib::MPEG::File.open('file.mp3') { |file| file.id3v2_tag }`

Error:

```
/usr/local/bundle/gems/taglib-ruby-0.7.1/lib/taglib/base.rb:10: [BUG] Segmentation fault at 0x0000562100000011
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0031 p:---- s:0176 e:000175 CFUNC  :close
c:0030 p:0021 s:0172 e:000171 METHOD /usr/local/bundle/gems/taglib-ruby-0.7.1/lib/taglib/base.rb:10
c:0029 p:0037 s:0165 e:000164 EVAL   (irb):5 [FINISH]
c:0028 p:---- s:0162 e:000161 CFUNC  :eval
c:0027 p:0021 s:0154 e:000153 METHOD /usr/local/lib/ruby/2.5.0/irb/workspace.rb:85
c:0026 p:0021 s:0146 e:000144 METHOD /usr/local/lib/ruby/2.5.0/irb/context.rb:380
c:0025 p:0017 s:0139 e:000138 BLOCK  /usr/local/lib/ruby/2.5.0/irb.rb:491
c:0024 p:0025 s:0129 e:000128 METHOD /usr/local/lib/ruby/2.5.0/irb.rb:623
c:0023 p:0008 s:0123 e:000122 BLOCK  /usr/local/lib/ruby/2.5.0/irb.rb:488
c:0022 p:0100 s:0118 e:000117 BLOCK  /usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:246 [FINISH]
c:0021 p:---- s:0114 e:000113 CFUNC  :loop
c:0020 p:0006 s:0110 e:000109 BLOCK  /usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:232 [FINISH]
c:0019 p:---- s:0107 e:000106 CFUNC  :catch
c:0018 p:0012 s:0102 e:000101 METHOD /usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:231
c:0017 p:0029 s:0098 E:001f30 METHOD /usr/local/lib/ruby/2.5.0/irb.rb:487
c:0016 p:0005 s:0094 e:000093 BLOCK  /usr/local/lib/ruby/2.5.0/irb.rb:428 [FINISH]
c:0015 p:---- s:0091 e:000090 CFUNC  :catch
c:0014 p:0063 s:0086 E:001208 METHOD /usr/local/lib/ruby/2.5.0/irb.rb:427
c:0013 p:0102 s:0081 e:000080 METHOD /usr/local/lib/ruby/2.5.0/irb.rb:383
c:0012 p:0174 s:0075 e:000074 METHOD /usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:62
c:0011 p:0011 s:0071 e:000070 METHOD /usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:17
c:0010 p:0057 s:0066 e:000065 METHOD /usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:97
c:0009 p:0064 s:0062 e:000061 METHOD /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27
c:0008 p:0047 s:0054 e:000053 METHOD /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126
c:0007 p:0259 s:0047 e:000046 METHOD /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387
c:0006 p:0043 s:0034 e:000033 METHOD /usr/local/bundle/gems/railties-5.1.7/lib/rails/command/base.rb:63
c:0005 p:0134 s:0027 e:000026 METHOD /usr/local/bundle/gems/railties-5.1.7/lib/rails/command.rb:44
c:0004 p:0087 s:0016 e:000015 TOP    /usr/local/bundle/gems/railties-5.1.7/lib/rails/commands.rb:16 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :require
c:0002 p:0051 s:0006 e:000005 EVAL   ./bin/rails:8 [FINISH]
c:0001 p:0000 s:0003 E:001420 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
./bin/rails:8:in `<main>'
./bin/rails:8:in `require'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:97:in `perform'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:17:in `start'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/commands/console/console_command.rb:62:in `start'
/usr/local/lib/ruby/2.5.0/irb.rb:383:in `start'
/usr/local/lib/ruby/2.5.0/irb.rb:427:in `run'
/usr/local/lib/ruby/2.5.0/irb.rb:427:in `catch'
/usr/local/lib/ruby/2.5.0/irb.rb:428:in `block in run'
/usr/local/lib/ruby/2.5.0/irb.rb:487:in `eval_input'
/usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.5.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.5.0/irb.rb:488:in `block in eval_input'
/usr/local/lib/ruby/2.5.0/irb.rb:623:in `signal_status'
/usr/local/lib/ruby/2.5.0/irb.rb:491:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.5.0/irb/context.rb:380:in `evaluate'
/usr/local/lib/ruby/2.5.0/irb/workspace.rb:85:in `evaluate'
/usr/local/lib/ruby/2.5.0/irb/workspace.rb:85:in `eval'
(irb):5:in `irb_binding'
/usr/local/bundle/gems/taglib-ruby-0.7.1/lib/taglib/base.rb:10:in `open'
/usr/local/bundle/gems/taglib-ruby-0.7.1/lib/taglib/base.rb:10:in `close'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f95b5fb05a7 RBP: 0x0000562100000001 RSP: 0x00007fff039538b0
 RAX: 0x000056212d23b2d8 RBX: 0x0000000000000020 RCX: 0x00007f95c7e4aa10
 RDX: 0x00000000b6571dd1 RDI: 0x00007fff039538e8 RSI: 0x00007fff039536e0
  R8: 0x0000000000000002  R9: 0x0000000000000041 R10: 0x0000000000000000
 R11: 0x0000000000000000 R12: 0x4000000000000000 R13: 0x4000000000000020
 R14: 0x00007fff039538e8 R15: 0x00007fff039538d0 EFL: 0x0000000000010293
```

Clang:
```
/app# clang -v
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

libtag1-dev: `1.11.1+dfsg.1-0.1`

Error appears only on Google PLatform, on local machine and on Heroku everything works fine.

What could be the problem?

**Comment by jacobvosmaer** [comment]
Sounds like it could be a Clang problem. Have you established that on the
server, the C extensions of taglib-ruby were compiled using Clang? I can't
tell from the output.

If the server is using Clang you could try getting it to use GCC instead.
This might help:
https://github.com/robinst/taglib-ruby#os-x-c-compiler-override

Op di 3 mrt. 2020 om 14:41 schreef Roman <notifications@github.com>:

**Comment by oksromn** [comment]
@jacobvosmaer When using _gcc_ instead of _clang_, same error occurs.

**Comment by robinst** [comment]
Hm, does the segmentation fault also occur when you do this?:

```
TagLib::MPEG::File.open('file.mp3') { |file| file.id3v2_tag.title }
```

**Comment by oksromn** [comment]
@robinst  Yes, in this case, an error also occurs.
It appears when I try to open a file.

**Comment by Tressa-Sanders** [comment]
I have this problem too but only on my CENT OS 7 production sever. On my local dev server, I don't have this issue. I'm also only getting it when I do anything with the database. The different there also is that I'm using MySQL on the dev machin and MariaDB on the production server.

**Comment by robinst** [comment]
@oksromn Can you please try again with a newer release of taglib-ruby and taglib?
